--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: myapp-v1 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: myapp 
      version: "v1.0" 
  template: 
    metadata: 
      labels: 
        app: myapp 
        version: "v1.0" 
      annotations: 
    spec: 
      containers: 
        - name: myapp-v1 
          image: kurtay/test-app
          ports: 
            - containerPort: 5000 
          env:
          - name: APP_MESSAGE
            value: "Version: v1.0"
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: myapp-v1-svc
  labels: 
    app: myapp 
spec: 
  ports: 
    - port: 80 
      targetPort: 5000 
  selector: 
    app: myapp
    version: "v1.0" 